version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:latest

  web:
    build: .
    command: "bundle exec foreman start"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=development
    volumes:
      - .:/app

volumes:
  dbdata:
